class AlreadyStartedException(Exception):
    pass


class NotStartedException(Exception):
    pass
